sudo: false
language: python
services:
- memcached
- mysql
- redis-server
branches:
  only:
  - master
install:
- pip install --upgrade pip wheel virtualenv
- pip install nox-automation
script:
- nox -s lint
